import Link from "next/link";

import { listAccountingPeriods } from "@/features/accounting-periods/service";
import { monthNames } from "@/features/accounting-periods/validation";
import type { BankDeposit } from "@/features/bank-deposits/types";
import { parseDepositId } from "@/features/bank-deposits/validation";
import { getActiveCompanyId } from "@/features/company-context/service";
import { confirmReconciliationAction, processExactReconciliationsAction } from "@/features/reconciliation/actions";
import { UndoReconciliationForm } from "@/features/reconciliation/components/undo-form";
import { getReconciliationWorkspace } from "@/features/reconciliation/service";
import type { MatchType, ReconciliationRow, ReconciliationWorkspace } from "@/features/reconciliation/types";
import { parseAmountFilter, parseMatchType } from "@/features/reconciliation/validation";

export const dynamic = "force-dynamic";

const inputClass = "mt-2 w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 outline-none focus:border-cyan-500 focus:ring-3 focus:ring-cyan-100";
const errors: Record<string, string> = {
  "invalid-request": "La solicitud no es válida.", INVALID_CONTEXT: "El monto esperado y el depósito deben pertenecer a la misma empresa y periodo.", DEPOSIT_UNAVAILABLE: "El depósito ya no está disponible.", EXACTS_PENDING: "Procesa primero todas las coincidencias exactas.", OUTSIDE_TOLERANCE: "La diferencia ya no está dentro de la tolerancia configurada.", ALREADY_RECONCILED: "El depósito o monto esperado ya fue conciliado.", RECONCILIATION_NOT_FOUND: "La conciliación ya no existe.", "save-failed": "No fue posible completar la conciliación.",
};

export default async function ReconciliationPage({ searchParams }: PageProps<"/conciliacion">) {
  const query = await searchParams;
  const periodId = parseDepositId(query.periodId);
  const companyId = await getActiveCompanyId();
  const periods = companyId ? await listAccountingPeriods({ search: "", companyId, year: null, status: "all" }) : [];
  const period = periods.find((item) => item.id === periodId);
  const workspace = period ? await getReconciliationWorkspace(period.id) : null;
  const stateFilter = typeof query.state === "string" ? query.state : "all";
  const matchType = parseMatchType(query.matchType);
  const accountId = parseDepositId(query.accountId);
  const amount = parseAmountFilter(query.amount);
  const message = messageText(query.message, query.count);
  const error = typeof query.error === "string" ? errors[query.error] : null;
  const rows = workspace ? workspace.rows.filter((row) => matchesFilters(row, stateFilter, matchType, accountId, amount)) : [];
  const accountOptions = workspace ? allAccountOptions(workspace) : [];

  return <div>{message ? <p className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</p> : null}{error ? <p className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-700">Operación / Conciliación</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Conciliación por periodo</h1><p className="mt-2 text-sm text-slate-500">Relaciona cada monto esperado con un único depósito recibido.</p></div>
    {companyId ? <form className="mt-6 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-[2fr_auto] sm:items-end" method="get"><Field label="Periodo mensual"><select className={inputClass} defaultValue={periodId ?? ""} name="periodId" required><option value="">Selecciona un periodo</option>{periods.map((item) => <option key={item.id} value={item.id}>{monthNames[item.month - 1]} {item.year}</option>)}</select></Field><button className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700" type="submit">Consultar</button></form> : <section className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-10 text-center text-sm text-slate-600">Selecciona una empresa activa desde el encabezado.</section>}
    {!period || !workspace ? <section className="mt-5 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><p className="font-semibold text-slate-800">Selecciona una empresa y un periodo.</p><p className="mt-1 text-sm text-slate-500">La conciliación se realiza únicamente dentro del periodo elegido.</p></section> : <Workspace periodId={period.id} periodLabel={`${period.companyName} · ${monthNames[period.month - 1]} ${period.year}`} workspace={workspace} rows={rows} accountOptions={accountOptions} filters={{ stateFilter, matchType, accountId, amount }} />}
  </div>;
}

function Workspace({ accountOptions, filters, periodId, periodLabel, rows, workspace }: { accountOptions: Array<{ id: number; label: string }>; filters: { stateFilter: string; matchType: MatchType | null; accountId: number | null; amount: string | null }; periodId: number; periodLabel: string; rows: ReconciliationRow[]; workspace: ReconciliationWorkspace }) {
  const pendingCents = Math.max(0, workspace.totalExpectedCents - workspace.totalReconciledCents);
  const availableCents = workspace.availableDeposits.reduce((sum, deposit) => sum + cents(deposit.amount), 0);
  return <><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">{periodLabel}</h2><p className="mt-1 text-sm text-slate-500">Tolerancia para sugerencias similares: ±{formatMoney(workspace.tolerance)}</p></div><form action={processExactReconciliationsAction}><input name="periodId" type="hidden" value={periodId} /><button className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700 disabled:cursor-not-allowed disabled:opacity-50" disabled={!workspace.exactMatchCount} type="submit">Procesar exactas ({workspace.exactMatchCount})</button></form></div>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Summary label="Total esperado" value={formatCents(workspace.totalExpectedCents)} /><Summary label="Total recibido" value={formatCents(workspace.totalReceivedCents)} /><Summary label="Total conciliado" value={formatCents(workspace.totalReconciledCents)} /><Summary label="Total pendiente" value={formatCents(pendingCents)} /><Summary detail={`${workspace.availableDeposits.length} movimientos`} label="Depósitos disponibles" value={formatCents(availableCents)} /><Summary detail="requieren confirmación" label="Similares pendientes" value={String(workspace.similarSuggestionCount)} /></section>
    <form className="mt-5 grid gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-5" method="get"><input name="periodId" type="hidden" value={periodId} /><Field label="Estado"><select className={inputClass} defaultValue={filters.stateFilter} name="state"><option value="all">Todos</option><option value="pending">Pendiente</option><option value="similar">Similar pendiente</option><option value="reconciled">Conciliado</option></select></Field><Field label="Tipo"><select className={inputClass} defaultValue={filters.matchType ?? ""} name="matchType"><option value="">Todos</option><option value="exact">Exacto</option><option value="similar">Similar</option><option value="manual">Manual</option></select></Field><Field label="Banco/cuenta"><select className={inputClass} defaultValue={filters.accountId ?? ""} name="accountId"><option value="">Todos</option>{accountOptions.map((account) => <option key={account.id} value={account.id}>{account.label}</option>)}</select></Field><Field label="Importe"><input className={inputClass} defaultValue={filters.amount ?? ""} inputMode="decimal" name="amount" placeholder="25000.00" /></Field><div className="flex items-end gap-2"><button className="flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50" type="submit">Filtrar</button><Link className="rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-50" href={`/conciliacion?periodId=${periodId}`}>Limpiar</Link></div></form>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Montos esperados y coincidencias</h2><p className="mt-1 text-xs text-slate-500">{rows.length} registros visibles</p></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Referencia esperada</th><th className="px-4 py-3">Esperado</th><th className="px-4 py-3">Recibido</th><th className="px-4 py-3">Diferencia</th><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Banco/cuenta</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Estado</th><th className="px-5 py-3">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <ReconciliationTableRow key={row.expected.id} periodId={periodId} row={row} availableDeposits={workspace.availableDeposits} />)}</tbody></table></div> : <div className="px-6 py-12 text-center text-sm text-slate-500">No hay registros que coincidan con los filtros.</div>}</section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Depósitos disponibles sin utilizar</h2><p className="mt-1 text-xs text-slate-500">Permanecen visibles hasta que se relacionen con un monto esperado.</p></div>{workspace.availableDeposits.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Fecha</th><th className="px-4 py-3">Banco/cuenta</th><th className="px-4 py-3">Monto</th><th className="px-4 py-3">Referencia</th><th className="px-5 py-3">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{workspace.availableDeposits.map((deposit) => <tr key={deposit.id}><td className="px-5 py-4 text-slate-600">{formatDate(deposit.depositDate)}</td><td className="px-4 py-4 text-slate-600">{deposit.bankName} · {deposit.accountAlias}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatMoney(deposit.amount)}</td><td className="px-4 py-4 text-slate-600">{deposit.reference || "—"}</td><td className="px-5 py-4"><Badge tone="amber">Sin conciliar</Badge></td></tr>)}</tbody></table></div> : <div className="px-6 py-10 text-center text-sm text-slate-500">No hay depósitos disponibles.</div>}</section>
  </>;
}

function ReconciliationTableRow({ availableDeposits, periodId, row }: { availableDeposits: BankDeposit[]; periodId: number; row: ReconciliationRow }) {
  const candidate = row.reconciliation?.deposit ?? row.exactCandidate?.deposit ?? row.similarCandidates[0]?.deposit ?? null;
  const difference = row.reconciliation?.difference ?? row.exactCandidate?.difference ?? row.similarCandidates[0]?.difference ?? null;
  return <tr className="align-top"><td className="max-w-64 px-5 py-4 text-xs text-slate-500">{referenceText(row.expected.referenceData)}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatMoney(row.expected.amount)}</td><td className="px-4 py-4 font-semibold text-slate-900">{candidate ? formatMoney(candidate.amount) : "—"}</td><td className="px-4 py-4 text-slate-600">{difference ? formatDifference(difference) : "—"}</td><td className="px-4 py-4 text-slate-600">{candidate ? formatDate(candidate.depositDate) : "—"}</td><td className="px-4 py-4 text-slate-600">{candidate ? `${candidate.bankName} · ${candidate.accountAlias}` : "—"}</td><td className="px-4 py-4 text-slate-600">{typeLabel(row)}</td><td className="px-4 py-4">{rowStatus(row)}</td><td className="px-5 py-4"><RowActions availableDeposits={availableDeposits} periodId={periodId} row={row} /></td></tr>;
}

function RowActions({ availableDeposits, periodId, row }: { availableDeposits: BankDeposit[]; periodId: number; row: ReconciliationRow }) {
  if (row.reconciliation) return <UndoReconciliationForm periodId={periodId} reconciliationId={row.reconciliation.id} />;
  return <div className="w-72 space-y-2">{row.similarCandidates.length ? <details className="rounded-lg border border-amber-200 bg-amber-50"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-amber-800">Revisar {row.similarCandidates.length} similar{row.similarCandidates.length === 1 ? "" : "es"}</summary><div className="space-y-2 border-t border-amber-100 p-2">{row.similarCandidates.map((candidate, index) => <form action={confirmReconciliationAction} className="rounded-md bg-white p-2 text-xs" key={candidate.deposit.id}><input name="periodId" type="hidden" value={periodId} /><input name="expectedAmountId" type="hidden" value={row.expected.id} /><input name="bankDepositId" type="hidden" value={candidate.deposit.id} /><input name="matchType" type="hidden" value="similar" /><p className="font-semibold text-slate-900">{formatMoney(candidate.deposit.amount)} · {formatDifference(candidate.difference)}{index === 0 && row.similarCandidates.length > 1 ? " · menor diferencia" : ""}</p><p className="mt-1 text-slate-500">{candidate.deposit.bankName} · {candidate.deposit.accountAlias} · {formatDate(candidate.deposit.depositDate)}</p><button className="mt-2 rounded-md bg-amber-600 px-2.5 py-1.5 font-semibold text-white hover:bg-amber-700" type="submit">Confirmar similar</button></form>)}</div></details> : null}{availableDeposits.length ? <details className="rounded-lg border border-slate-200"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-slate-700">Conciliar manualmente</summary><form action={confirmReconciliationAction} className="space-y-2 border-t border-slate-100 p-2"><input name="periodId" type="hidden" value={periodId} /><input name="expectedAmountId" type="hidden" value={row.expected.id} /><input name="matchType" type="hidden" value="manual" /><select className="w-full rounded-md border border-slate-300 bg-white px-2 py-2 text-xs" name="bankDepositId" required><option value="">Selecciona depósito</option>{availableDeposits.map((deposit) => <option key={deposit.id} value={deposit.id}>{formatMoney(deposit.amount)} · {deposit.bankName}/{deposit.accountAlias} · {formatDate(deposit.depositDate)}</option>)}</select><button className="rounded-md bg-slate-700 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-slate-800" type="submit">Confirmar manual</button></form></details> : null}</div>;
}

function matchesFilters(row: ReconciliationRow, state: string, type: MatchType | null, accountId: number | null, amount: string | null): boolean {
  if (state === "pending" && (row.reconciliation || row.similarCandidates.length)) return false;
  if (state === "similar" && (row.reconciliation || !row.similarCandidates.length)) return false;
  if (state === "reconciled" && !row.reconciliation) return false;
  const inferredType = row.reconciliation?.matchType ?? (row.exactCandidate ? "exact" : row.similarCandidates.length ? "similar" : null);
  if (type && inferredType !== type) return false;
  const deposits = [row.reconciliation?.deposit, row.exactCandidate?.deposit, ...row.similarCandidates.map((item) => item.deposit)].filter((item): item is BankDeposit => Boolean(item));
  if (accountId && !deposits.some((deposit) => deposit.bankAccountId === accountId)) return false;
  if (amount && row.expected.amount !== amount && !deposits.some((deposit) => deposit.amount === amount)) return false;
  return true;
}

function allAccountOptions(workspace: ReconciliationWorkspace) { const deposits = [...workspace.availableDeposits, ...workspace.rows.flatMap((row) => row.reconciliation ? [row.reconciliation.deposit] : [])]; return Array.from(new Map(deposits.map((deposit) => [deposit.bankAccountId, { id: deposit.bankAccountId, label: `${deposit.bankName} · ${deposit.accountAlias}` }])).values()); }
function typeLabel(row: ReconciliationRow): string { if (row.reconciliation) return row.reconciliation.matchType === "exact" ? "Exacta" : row.reconciliation.matchType === "similar" ? "Similar" : "Manual"; if (row.exactCandidate) return "Exacta pendiente"; if (row.similarCandidates.length) return row.similarCandidates.length > 1 ? `${row.similarCandidates.length} similares` : "Similar"; return "—"; }
function rowStatus(row: ReconciliationRow) { if (row.reconciliation?.matchType === "exact") return <Badge tone="emerald">Conciliado exacto</Badge>; if (row.reconciliation?.matchType === "similar") return <Badge tone="cyan">Conciliado con diferencia</Badge>; if (row.reconciliation?.matchType === "manual") return <Badge tone="cyan">Conciliado manual</Badge>; if (row.similarCandidates.length) return <Badge tone="amber">Similar pendiente</Badge>; return <Badge tone="slate">Pendiente</Badge>; }
function Badge({ children, tone }: { children: React.ReactNode; tone: "amber" | "cyan" | "emerald" | "slate" }) { const colors = { amber: "bg-amber-50 text-amber-700", cyan: "bg-cyan-50 text-cyan-700", emerald: "bg-emerald-50 text-emerald-700", slate: "bg-slate-100 text-slate-600" }; return <span className={`inline-block rounded-full px-2.5 py-1 text-xs font-semibold ${colors[tone]}`}>{children}</span>; }
function Summary({ detail, label, value }: { detail?: string; label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-2 text-xl font-semibold text-slate-900">{value}</p>{detail ? <p className="mt-1 text-xs text-slate-400">{detail}</p> : null}</div>; }
function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="text-xs font-semibold text-slate-600">{label}{children}</label>; }
function messageText(value: unknown, count: unknown): string | null { if (value === "exact") return `Se conciliaron ${typeof count === "string" ? count : "0"} coincidencias exactas.`; if (value === "confirmed") return "La conciliación se confirmó correctamente."; if (value === "undone") return "La conciliación se deshizo y el depósito volvió a estar disponible."; return null; }
function referenceText(data: Record<string, string>): string { return Object.entries(data).filter(([, value]) => value).slice(0, 4).map(([key, value]) => `${key}: ${value}`).join(" · ") || "—"; }
function cents(value: string): number { const [integer, decimal = "00"] = value.split("."); return Number(integer) * 100 + Number(decimal.padEnd(2, "0").slice(0, 2)); }
function formatMoney(value: string): string { const negative = value.startsWith("-"); const [integer, decimals] = value.replace("-", "").split("."); return `${negative ? "-" : ""}$${integer.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${decimals}`; }
function formatCents(value: number): string { return formatMoney(`${Math.floor(value / 100)}.${String(value % 100).padStart(2, "0")}`); }
function formatDifference(value: string): string { return value === "0.00" ? "$0.00" : `${value.startsWith("-") ? "-" : "+"}$${value.replace("-", "")}`; }
function formatDate(value: string): string { return new Date(`${value}T12:00:00`).toLocaleDateString("es-MX", { dateStyle: "medium" }); }
