import Link from "next/link";
import { notFound } from "next/navigation";

import { getCompany } from "@/features/companies/service";
import { getPurchaseOrderSettings } from "@/features/purchase-order-settings/service";
import { PurchaseOrderStatusActions } from "@/features/purchase-orders/components/status-actions";
import { DriveDocumentCard } from "@/features/purchase-orders/components/drive-document-card";
import { getPurchaseOrder } from "@/features/purchase-orders/service";
import type { PurchaseOrderStatus } from "@/features/purchase-orders/types";
import { parsePurchaseOrderId } from "@/features/purchase-orders/validation";
import { validateActiveCompany } from "@/features/company-context/service";

const messages: Record<string, string> = { created: "La orden se guardó y el folio quedó reservado.", updated: "La orden se actualizó correctamente.", confirmed: "La orden quedó confirmada.", cancelled: "La orden quedó cancelada, se conserva en el historial y su PDF fue eliminado de Drive cuando existía.", "drive-saved": "El PDF se guardó correctamente en Google Drive.", "drive-replaced": "El PDF existente se reemplazó correctamente en Google Drive.", "accounting-sent": "La orden quedó marcada como enviada a contabilidad." };
const errors: Record<string, string> = { "status-not-allowed": "El estado actual ya no permite esa operación.", "status-failed": "No fue posible cambiar el estado.", "drive-not-allowed": "Solo las órdenes confirmadas pueden guardarse en Drive.", "drive-already-stored": "La orden ya tiene un PDF en Drive. Usa la acción explícita de reemplazo.", "drive-not-stored": "La orden todavía no tiene un PDF que pueda reemplazarse.", "drive-not-configured": "La configuración del servidor para Google Drive está incompleta.", "drive-file-exists": "Ya existe un archivo con ese nombre en la carpeta de Drive; no se creó un duplicado.", "drive-upload-failed": "No fue posible guardar el PDF en Google Drive. La orden permanece intacta.", "drive-delete-not-configured": "Configura Google Drive antes de cancelar una orden que ya tiene PDF.", "drive-delete-failed": "No fue posible eliminar el PDF de Drive. La orden no fue cancelada.", "accounting-not-allowed": "La orden debe estar confirmada y guardada en Drive antes de enviarse a contabilidad.", "accounting-failed": "No fue posible actualizar el estado de contabilidad." };
const statusLabels = { draft: "Borrador", confirmed: "Confirmada", cancelled: "Cancelada" } as const;

export default async function PurchaseOrderDetailPage({ params, searchParams }: PageProps<"/ordenes-compra/[id]">) {
  const { id: rawId } = await params;
  const id = parsePurchaseOrderId(rawId);
  if (!id) notFound();
  const order = await getPurchaseOrder(id);
  if (!order) notFound();
  await validateActiveCompany(order.companyId);
  const [company, settings, query] = await Promise.all([getCompany(order.companyId), getPurchaseOrderSettings(order.companyId), searchParams]);
  if (!company) notFound();
  const message = typeof query.message === "string" ? messages[query.message] : null;
  const error = typeof query.error === "string" ? errors[query.error] : null;

  return <div className="mx-auto max-w-6xl">
    {message ? <p className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</p> : null}{error ? <p className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-700">{order.companyName} / Órdenes</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{order.orderNumber}</h1><Status status={order.status} /></div><p className="mt-2 text-sm text-slate-500">Creada {formatDateTime(order.createdAt)}</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50" href="/ordenes-compra">Volver</Link><a className="rounded-lg border border-cyan-200 bg-cyan-50 px-4 py-2.5 text-sm font-semibold text-cyan-700 hover:bg-cyan-100" href={`/api/ordenes-compra/${id}/pdf`} rel="noreferrer" target="_blank">Vista previa PDF</a>{order.status === "confirmed" ? <a className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700" href={`/api/ordenes-compra/${id}/pdf?download=1`}>Generar PDF</a> : null}{order.status === "draft" ? <Link className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700" href={`/ordenes-compra/${id}/editar`}>Editar</Link> : null}</div></div>
    <section className="mt-6 grid gap-4 lg:grid-cols-2"><Info title="Proveedor"><Detail label="Razón social" value={order.supplierLegalName} /><Detail label="RFC" value={order.supplierTaxId} /><Detail label="Domicilio fiscal" value={order.supplierAddress} /><Detail label="Teléfono" value={order.supplierPhone} /></Info><Info title="Orden"><Detail label="Empresa" value={order.companyName} /><Detail label="Fecha de expedición" value={formatDate(order.orderDate)} /><Detail label="Fecha de entrega" value={formatDate(order.deliveryDate)} /><Detail label="Configuración" value={settings ? "Disponible para la salida documental" : "Sin configuración adicional"} /></Info></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Partidas</h2></div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Producto</th><th className="px-3 py-3">Precio</th><th className="px-3 py-3">Cantidad</th><th className="px-3 py-3">Descuento</th><th className="px-3 py-3">IVA</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{order.items.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-semibold text-slate-900">{item.productName}</p><p className="mt-1 text-xs text-slate-500">{item.productReference ?? "Sin referencia"} · {item.unit}</p>{item.description ? <p className="mt-1 max-w-lg whitespace-pre-wrap text-xs text-slate-400">{item.description}</p> : null}</td><td className="px-3 py-4 tabular-nums">{formatMoney(item.unitPrice)}</td><td className="px-3 py-4 tabular-nums">{formatQuantity(item.quantity)}</td><td className="px-3 py-4 tabular-nums">{formatMoney(item.discount)}</td><td className="px-3 py-4">{formatTax(item.taxRate)}</td><td className="px-5 py-4 text-right font-semibold tabular-nums">{formatMoney(item.total)}</td></tr>)}</tbody></table></div><div className="divide-y divide-slate-100 md:hidden">{order.items.map((item) => <article className="p-4" key={item.id}><p className="font-semibold text-slate-900">{item.productName}</p><p className="mt-1 text-xs text-slate-500">{item.productReference ?? "Sin referencia"} · {formatQuantity(item.quantity)} {item.unit}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-sm"><Detail label="Precio" value={formatMoney(item.unitPrice)} /><Detail label="IVA" value={formatTax(item.taxRate)} /><Detail label="Total" value={formatMoney(item.total)} /></dl></article>)}</div></section>
    {order.notes ? <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Observaciones</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{order.notes}</p></section> : null}
    <DriveDocumentCard errorCode={typeof query.error === "string" ? query.error : null} order={order} />
    <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_380px]"><div>{order.status !== "cancelled" ? <PurchaseOrderStatusActions hasDriveFile={Boolean(order.driveFileId)} id={id} status={order.status} /> : null}</div><div className="rounded-xl border border-slate-200 bg-white p-5"><dl className="space-y-3"><Total label="Subtotal" value={order.subtotal} /><Total label="Descuento" value={order.discountTotal} /><Total label="IVA" value={order.taxTotal} /><Total emphasis label="Total" value={order.total} /></dl></div></section>
  </div>;
}

function Info({ children, title }: { children: React.ReactNode; title: string }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-sm font-semibold text-slate-900">{title}</h2><dl className="grid gap-4 sm:grid-cols-2">{children}</dl></section>; }
function Detail({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-xs font-medium text-slate-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-medium text-slate-700">{value || "—"}</dd></div>; }
function Total({ emphasis = false, label, value }: { emphasis?: boolean; label: string; value: string }) { return <div className={`flex justify-between ${emphasis ? "border-t border-slate-200 pt-3 text-lg font-bold" : "text-sm text-slate-600"}`}><dt>{label}</dt><dd>{formatMoney(value)}</dd></div>; }
function Status({ status }: { status: PurchaseOrderStatus }) { const tone = status === "confirmed" ? "bg-emerald-50 text-emerald-700" : status === "cancelled" ? "bg-slate-100 text-slate-500" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{statusLabels[status]}</span>; }
function formatMoney(value: string): string { return new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" }).format(Number(value)); }
function formatDate(value: string): string { return new Date(`${value}T12:00:00`).toLocaleDateString("es-MX", { dateStyle: "long" }); }
function formatDateTime(value: Date): string { return value.toLocaleString("es-MX", { dateStyle: "long", timeStyle: "short" }); }
function formatTax(value: string): string { return `${Number(value).toLocaleString("es-MX", { maximumFractionDigits: 2 })}%`; }
function formatQuantity(value: string): string { return Number(value).toLocaleString("es-MX", { maximumFractionDigits: 4 }); }
