import Link from "next/link";
import { notFound } from "next/navigation";

import { setPeriodStatusAction } from "@/features/accounting-periods/actions";
import { getAccountingPeriod } from "@/features/accounting-periods/service";
import type { PeriodStatus } from "@/features/accounting-periods/types";
import { monthNames, parsePeriodId, periodStatusLabels } from "@/features/accounting-periods/validation";
import { listDeposits } from "@/features/bank-deposits/service";
import type { DepositStatus } from "@/features/bank-deposits/types";
import { parseDepositDate, parseDepositId, parseDepositStatus } from "@/features/bank-deposits/validation";
import { getDeliverySummary, listCashDeliveries } from "@/features/cash-deliveries/service";
import { getActiveCompanyId } from "@/features/company-context/service";
import { moneyToCents } from "@/features/expected-amounts/money";
import { listExpectedAmounts } from "@/features/expected-amounts/service";

const messages: Record<string, string> = { created: "El periodo se creó correctamente.", updated: "Las observaciones se actualizaron correctamente.", "status-updated": "El estado se actualizó correctamente." };
const filterClass = "mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900";

export default async function PeriodDetailPage({ params, searchParams }: PageProps<"/periodos/[id]">) {
  const id = parsePeriodId((await params).id);
  if (!id) notFound();
  const query = await searchParams;
  const accountId = parseDepositId(query.accountId);
  const depositDate = parseDepositDate(query.date);
  const depositStatus = parseDepositStatus(query.depositStatus);
  const batchId = parseDepositId(query.batchId);
  const [period, activeCompanyId] = await Promise.all([getAccountingPeriod(id), getActiveCompanyId()]);
  if (!period || period.companyId !== activeCompanyId) notFound();
  const [expectedAmounts, allDeposits, cashDeliveries, deliverySummary] = await Promise.all([listExpectedAmounts(id), listDeposits({ companyId: activeCompanyId, accountingPeriodId: id, bankAccountId: null, depositDate: null, status: null, batchId: null }), listCashDeliveries(id), getDeliverySummary(id)]);
  const deposits = allDeposits.filter((deposit) => (!accountId || deposit.bankAccountId === accountId) && (!depositDate || deposit.depositDate === depositDate) && (!depositStatus || deposit.status === depositStatus) && (!batchId || deposit.batchId === batchId));
  const accounts = Array.from(new Map(allDeposits.map((deposit) => [deposit.bankAccountId, { id: deposit.bankAccountId, label: `${deposit.bankName} · ${deposit.accountAlias}` }])).values());
  const batches = Array.from(new Set(allDeposits.flatMap((deposit) => deposit.batchId ? [deposit.batchId] : [])));
  const batchCount = batches.length;
  const message = typeof query.message === "string" ? messages[query.message] : undefined;

  return <div className="mx-auto max-w-5xl">{message ? <p className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</p> : null}<div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-700">Periodos / Detalle</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{period.companyName} · {monthNames[period.month - 1]} {period.year}</h1><PeriodStatusBadge status={period.status} /></div></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50" href="/periodos">Volver</Link><Link className="rounded-lg border border-cyan-600 bg-white px-4 py-2.5 text-sm font-semibold text-cyan-700 hover:bg-cyan-50" href={`/conciliacion?companyId=${period.companyId}&periodId=${id}`}>Conciliar</Link><Link className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700" href={`/periodos/${id}/editar`}>Editar observaciones</Link></div></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><dl className="grid sm:grid-cols-2"><Detail label="Empresa" value={period.companyName} /><Detail label="Periodo" value={`${monthNames[period.month - 1]} ${period.year}`} /><Detail label="Estado" value={periodStatusLabels[period.status]} /><Detail label="Fecha de creación" value={formatDate(period.createdAt)} /><Detail className="sm:col-span-2" label="Observaciones" value={period.notes || "Sin observaciones"} /></dl></section>
    <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><form action={setPeriodStatusAction} className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Estado del periodo</h2><p className="mt-1 text-sm text-slate-500">Los periodos cerrados permanecen visibles y pueden consultarse.</p></div><input name="id" type="hidden" value={period.id} /><input name="companyId" type="hidden" value={period.companyId} /><div className="flex flex-col gap-2 sm:flex-row"><select className="rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm" defaultValue={period.status} name="status">{(Object.keys(periodStatusLabels) as PeriodStatus[]).map((status) => <option key={status} value={status}>{periodStatusLabels[status]}</option>)}</select><button className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50" type="submit">Cambiar estado</button></div></form></section>
    <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Montos esperados</h2><p className="mt-1 text-sm text-slate-500">{expectedAmounts.length} registros importados individualmente.</p></div><Link className="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-600 hover:bg-slate-50" href={`/periodos/${id}/montos-esperados`}>Consultar montos</Link></div></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Depósitos recibidos</h2><p className="mt-1 text-sm text-slate-500">Total {formatDepositTotal(allDeposits.map((item) => item.amount))} · {allDeposits.length} depósitos · {batchCount} lotes</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-cyan-600 px-3 py-2 text-xs font-semibold text-cyan-700 hover:bg-cyan-50" href={`/depositos/multiples?periodId=${id}`}>Registrar lote</Link><Link className="rounded-lg bg-cyan-600 px-3 py-2 text-xs font-semibold text-white hover:bg-cyan-700" href={`/depositos/nuevo?periodId=${id}`}>Registrar depósito</Link></div></div>
      <form className="grid gap-3 border-b border-slate-100 bg-slate-50/60 p-4 sm:grid-cols-2 lg:grid-cols-5" method="get"><Filter label="Cuenta"><select className={filterClass} defaultValue={accountId ?? ""} name="accountId"><option value="">Todas</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.label}</option>)}</select></Filter><Filter label="Fecha"><input className={filterClass} defaultValue={depositDate ?? ""} name="date" type="date" /></Filter><Filter label="Estado"><select className={filterClass} defaultValue={depositStatus ?? ""} name="depositStatus"><option value="">Todos</option><option value="available">Disponible</option><option value="reconciled">Conciliado</option></select></Filter><Filter label="Lote"><select className={filterClass} defaultValue={batchId ?? ""} name="batchId"><option value="">Todos</option>{batches.map((batch) => <option key={batch} value={batch}>Lote #{batch}</option>)}</select></Filter><div className="flex items-end gap-2"><button className="flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-white" type="submit">Filtrar</button><Link className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-500 hover:bg-white" href={`/periodos/${id}`}>Limpiar</Link></div></form>
      {deposits.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Fecha</th><th className="px-4 py-3">Cuenta</th><th className="px-4 py-3">Monto</th><th className="px-4 py-3">Referencia</th><th className="px-4 py-3">Lote</th><th className="px-4 py-3">Estado</th><th className="px-5 py-3 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{deposits.map((deposit) => <tr key={deposit.id}><td className="px-5 py-4 text-slate-600">{formatDepositDate(deposit.depositDate)}</td><td className="px-4 py-4 text-slate-600">{deposit.bankName} · {deposit.accountAlias}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatDepositMoney(deposit.amount)}</td><td className="px-4 py-4 text-slate-600">{deposit.reference || "—"}</td><td className="px-4 py-4 text-slate-600">{deposit.batchId ? `#${deposit.batchId}` : "Individual"}</td><td className="px-4 py-4"><DepositStatusBadge status={deposit.status} /></td><td className="px-5 py-4 text-right"><Link className="text-xs font-semibold text-cyan-700 hover:underline" href={`/depositos/${deposit.id}`}>Ver</Link></td></tr>)}</tbody></table></div> : <div className="px-5 py-10 text-center text-sm text-slate-500">No hay depósitos que coincidan con los filtros.</div>}<div className="border-t border-slate-100 px-5 py-3 text-right"><Link className="text-xs font-semibold text-cyan-700 hover:underline" href={`/depositos?periodId=${id}`}>Consultar todos los depósitos</Link></div></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Entregas de efectivo</h2><p className="mt-1 text-sm text-slate-500">Guardado {formatDepositMoney(deliverySummary.totalStored)} · Entregado {formatDepositMoney(deliverySummary.totalDelivered)} · Pendiente {formatDepositMoney(deliverySummary.pendingBalance)} · {deliverySummary.deliveryCount} entregas</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-cyan-600 px-3 py-2 text-xs font-semibold text-cyan-700 hover:bg-cyan-50" href={`/entregas?periodId=${id}`}>Consultar historial</Link>{period.status !== "closed" ? <Link className="rounded-lg bg-cyan-600 px-3 py-2 text-xs font-semibold text-white hover:bg-cyan-700" href={`/entregas/nueva?periodId=${id}`}>Registrar entrega</Link> : null}</div></div>{cashDeliveries.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Folio</th><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Guardado</th><th className="px-4 py-3">Entregado</th><th className="px-4 py-3">Entrega</th><th className="px-4 py-3">Recibe</th><th className="px-4 py-3">Estado</th><th className="px-5 py-3 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{cashDeliveries.map((delivery) => <tr key={delivery.id}><td className="px-5 py-4 font-semibold text-slate-900">ENT-{String(delivery.id).padStart(6, "0")}</td><td className="px-4 py-4 text-slate-600">{formatDepositDate(delivery.deliveryDate)}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatDepositMoney(delivery.storedAmount)}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatDepositMoney(delivery.amount)}</td><td className="px-4 py-4 text-slate-600">{delivery.deliveredBy}</td><td className="px-4 py-4 text-slate-600">{delivery.receivedBy}</td><td className="px-4 py-4 text-slate-600">{delivery.status === "confirmed" ? "Firmada" : delivery.status === "cancelled" ? "Cancelada" : "Firma pendiente"}</td><td className="px-5 py-4 text-right"><Link className="text-xs font-semibold text-cyan-700 hover:underline" href={`/entregas/${delivery.id}`}>Ver</Link></td></tr>)}</tbody></table></div> : <div className="px-5 py-10 text-center text-sm text-slate-500">No hay entregas registradas en este periodo.</div>}</section>
  </div>;
}

function PeriodStatusBadge({ status }: { status: PeriodStatus }) { const tone = status === "open" ? "bg-emerald-50 text-emerald-700" : status === "review" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{periodStatusLabels[status]}</span>; }
function DepositStatusBadge({ status }: { status: DepositStatus }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${status === "available" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{status === "available" ? "Disponible" : "Conciliado"}</span>; }
function Detail({ className = "", label, value }: { className?: string; label: string; value: string }) { return <div className={`border-b border-slate-100 p-5 sm:p-6 sm:odd:border-r ${className}`}><dt className="text-xs font-medium text-slate-400">{label}</dt><dd className="mt-2 whitespace-pre-wrap text-sm font-medium text-slate-800">{value}</dd></div>; }
function Filter({ children, label }: { children: React.ReactNode; label: string }) { return <label className="text-xs font-semibold text-slate-600">{label}{children}</label>; }
function formatDate(date: Date): string { return date.toLocaleString("es-MX", { dateStyle: "long", timeStyle: "short" }); }
function formatDepositMoney(value: string): string { const [integer, decimals] = value.split("."); return `$${integer.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${decimals}`; }
function formatDepositTotal(values: string[]): string { const cents = values.reduce((sum, value) => sum + (moneyToCents(value) ?? 0), 0); return formatDepositMoney(`${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, "0")}`); }
function formatDepositDate(value: string): string { return new Date(`${value}T12:00:00`).toLocaleDateString("es-MX", { dateStyle: "medium" }); }
