import Link from "next/link";
import { notFound } from "next/navigation";

import { getAccountingPeriod } from "@/features/accounting-periods/service";
import { monthNames, parsePeriodId } from "@/features/accounting-periods/validation";
import { DeleteImportButton } from "@/features/expected-amounts/components/delete-import-button";
import { listExpectedAmountImports, listExpectedAmounts } from "@/features/expected-amounts/service";
import { getActiveCompanyId } from "@/features/company-context/service";

export const dynamic = "force-dynamic";

export default async function ExpectedAmountsPage({ params, searchParams }: PageProps<"/periodos/[id]/montos-esperados">) {
  const id = parsePeriodId((await params).id);
  if (!id) notFound();
  const [period, activeCompanyId] = await Promise.all([getAccountingPeriod(id), getActiveCompanyId()]);
  if (!period || period.companyId !== activeCompanyId) notFound();
  const [amounts, imports] = await Promise.all([listExpectedAmounts(id), listExpectedAmountImports(id)]);
  const query = await searchParams;
  const message = query.message === "imported" ? "Los montos esperados se importaron correctamente." : query.message === "deleted" ? "La importación y sus montos esperados se eliminaron correctamente." : null;
  const error = query.error === "import-reconciled" ? "No puedes eliminar una importación con montos ya conciliados. Primero debes deshacer esas conciliaciones." : query.error === "import-not-found" ? "La importación ya no existe." : query.error === "delete-failed" ? "No fue posible eliminar la importación." : null;
  const reconciled = amounts.filter((item) => item.matchType).length;

  return <div className="mx-auto max-w-6xl">{message ? <p className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</p> : null}{error ? <p className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-700">Periodos / Montos esperados</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{period.companyName} · {monthNames[period.month - 1]} {period.year}</h1><p className="mt-2 text-sm text-slate-500">Cada fila importada se conserva como un registro individual.</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50" href={`/periodos/${id}`}>Volver</Link><Link className="rounded-lg border border-cyan-600 bg-white px-4 py-2.5 text-sm font-semibold text-cyan-700 hover:bg-cyan-50" href={`/conciliacion?companyId=${period.companyId}&periodId=${id}`}>Conciliar</Link><Link className="rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700" href={`/periodos/${id}/montos-esperados/importar`}>Importar Excel</Link></div></div>
    {imports.length ? <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Archivos importados</h2><p className="mt-1 text-xs text-slate-500">Elimina aquí un Excel cargado por error antes de eliminar el periodo.</p></div><div className="divide-y divide-slate-100">{imports.map((item) => <div className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" key={item.id}><div><p className="text-sm font-semibold text-slate-900">{item.sourceName || `Importación #${item.id}`}</p><p className="mt-1 text-xs text-slate-500">{item.rowCount} filas · columna {item.amountColumn} · {item.reconciledCount} conciliadas · {formatDate(item.createdAt)}</p></div><DeleteImportButton importId={item.id} periodId={id} reconciledCount={item.reconciledCount} /></div>)}</div></section> : null}
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Summary label="Total" value={amounts.length} /><Summary label="Pendientes" value={amounts.length - reconciled} /><Summary label="Conciliados" value={reconciled} /></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Registros esperados</h2></div>{amounts.length ? <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Fila</th><th className="px-4 py-3">Importe</th><th className="px-4 py-3">Referencias</th><th className="px-4 py-3">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{amounts.map((item) => <tr key={item.id}><td className="px-5 py-4 text-slate-500">{item.sourceRowNumber}</td><td className="px-4 py-4 font-semibold text-slate-900">{formatMoney(item.amount)}</td><td className="px-4 py-4 text-xs text-slate-500">{referenceText(item.referenceData)}</td><td className="px-4 py-4"><Status matched={Boolean(item.matchType)} /></td></tr>)}</tbody></table></div><div className="divide-y divide-slate-100 lg:hidden">{amounts.map((item) => <article className="p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{formatMoney(item.amount)}</p><p className="mt-1 text-xs text-slate-400">Fila {item.sourceRowNumber}</p></div><Status matched={Boolean(item.matchType)} /></div><p className="mt-3 text-xs text-slate-500">{referenceText(item.referenceData)}</p></article>)}</div></> : <div className="px-6 py-14 text-center"><p className="font-semibold text-slate-800">No hay montos esperados.</p><p className="mt-1 text-sm text-slate-500">Importa un Excel para comenzar.</p></div>}</section>
  </div>;
}

function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></div>; }
function Status({ matched }: { matched: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${matched ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{matched ? "Conciliado" : "Pendiente"}</span>; }
function referenceText(data: Record<string, string>): string { return Object.entries(data).filter(([, value]) => value).slice(0, 5).map(([key, value]) => `${key}: ${value}`).join(" · ") || "—"; }
function formatMoney(value: string): string { const [integer, decimals] = value.split("."); return `$${integer.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${decimals}`; }
function formatDate(value: Date): string { return value.toLocaleDateString("es-MX", { dateStyle: "medium" }); }
