import Link from "next/link";

import { ReportFilters } from "@/features/reports/components/report-filters";
import { getDashboardReport, resolveReportContext } from "@/features/reports/service";
import type { DeliveryReportRow, PurchaseOrderReportRow, ReportFilters as Filters } from "@/features/reports/types";
import { getActiveCompanyId } from "@/features/company-context/service";

export const dynamic = "force-dynamic";
const moneyFormatter = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });
const quantityFormatter = new Intl.NumberFormat("es-MX", { maximumFractionDigits: 4 });

export default async function DashboardPage({ searchParams }: PageProps<"/dashboard">) {
  const context = await resolveReportContext(await searchParams, await getActiveCompanyId());
  const report = context.filters ? await getDashboardReport(context.filters) : null;
  const company = context.companies.find((item) => item.id === context.filters?.companyId);
  const period = context.periods.find((item) => item.id === context.filters?.periodId);

  return <div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-700">Administración / Reportes</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Dashboard operativo</h1><p className="mt-2 text-sm leading-6 text-slate-500">Información consolidada de la empresa y el periodo seleccionado, calculada desde los movimientos existentes.</p></div><Link className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2.5 text-center text-sm font-semibold text-amber-900 hover:bg-amber-100" href={profitHref(context.filters)}>Costo y utilidad</Link></div>
    <ReportFilters context={context} destination="/dashboard" />
    {!report || !context.filters ? <EmptyState hasCompanies={context.companies.length > 0} /> : <>
      <div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Vista consolidada</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{company?.label} · {period?.label}</h2></div><p className="text-xs text-slate-500">Las fechas y la cuenta bancaria se aplican donde existe ese dato.</p></div>
      <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5" aria-label="Indicadores principales">
        <Metric label="Total esperado" value={money(report.metrics.totalExpected)} />
        <Metric label="Total recibido" value={money(report.metrics.totalReceived)} />
        <Metric label="Total conciliado" value={money(report.metrics.totalReconciled)} />
        <Metric label="Pendiente de recibir" value={money(report.metrics.pendingToReceive)} tone="amber" />
        <Metric label="Depósitos sin conciliar" value={money(report.metrics.unmatchedDepositAmount)} detail={`${report.metrics.unmatchedDepositCount} movimientos`} tone="amber" />
        <Metric label="Total entregado" value={money(report.metrics.totalDelivered)} />
        <Metric label="Pendiente de entregar" value={money(report.metrics.pendingToDeliver)} tone="amber" />
        <Metric label="Órdenes confirmadas" value={String(report.metrics.purchaseOrderCount)} />
        <Metric label="Total de órdenes" value={money(report.metrics.purchaseOrderTotal)} />
      </section>

      <ReportSection description="Relación individual entre cada monto esperado y el depósito utilizado." title="Reporte de conciliación">
        <div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2 lg:grid-cols-5"><MiniMetric label="Esperados" value={report.reconciliation.summary.expectedCount} /><MiniMetric label="Exactos" value={report.reconciliation.summary.exactCount} /><MiniMetric label="Con diferencia" value={report.reconciliation.summary.differenceCount} /><MiniMetric label="Pendientes" value={report.reconciliation.summary.pendingCount} /><MiniMetric label="Depósitos libres" value={report.reconciliation.summary.unmatchedDepositCount} /></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><Th>Esperado</Th><Th>Referencia</Th><Th>Resultado</Th><Th>Depósito</Th><Th>Fecha / cuenta</Th><Th>Acción</Th></tr></thead><tbody className="divide-y divide-slate-100">{report.reconciliation.movements.map((row) => <tr key={row.expectedAmountId}><Td strong>{money(row.expectedAmount)}</Td><Td>{reference(row.referenceData)}</Td><Td><MatchBadge difference={row.difference} matchType={row.matchType} /></Td><Td>{row.depositAmount ? money(row.depositAmount) : "—"}</Td><Td>{row.depositDate ? <>{date(row.depositDate)}<span className="mt-1 block text-xs text-slate-400">{row.bankAccount}</span></> : "—"}</Td><Td>{row.depositId ? <Link className="font-semibold text-cyan-700 hover:text-cyan-900" href={`/depositos/${row.depositId}`}>Ver depósito</Link> : <span className="text-slate-400">Pendiente</span>}</Td></tr>)}</tbody></table></div>
        {report.reconciliation.movements.length === 0 ? <EmptyRows text="No hay montos esperados en este periodo." /> : null}
        <div className="border-t border-slate-200 bg-slate-50/60 px-5 py-3"><h3 className="text-sm font-semibold text-slate-800">Depósitos sin conciliar</h3></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white text-xs uppercase text-slate-500"><tr><Th>Fecha</Th><Th>Cuenta</Th><Th>Referencia</Th><Th>Monto</Th><Th>Acción</Th></tr></thead><tbody className="divide-y divide-slate-100">{report.reconciliation.unmatchedDeposits.map((row) => <tr key={row.id}><Td>{date(row.depositDate)}</Td><Td>{row.bankAccount}</Td><Td>{row.reference ?? "—"}</Td><Td strong>{money(row.amount)}</Td><Td><Link className="font-semibold text-cyan-700" href={`/depositos/${row.id}`}>Ver</Link></Td></tr>)}</tbody></table></div>
        {report.reconciliation.unmatchedDeposits.length === 0 ? <EmptyRows text="No hay depósitos pendientes con los filtros seleccionados." /> : null}
      </ReportSection>

      <ReportSection description="Efectivo guardado, entregado e historial independiente de los depósitos bancarios." title="Reporte de entregas">
        <div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2 lg:grid-cols-4"><MiniMetric label="Total guardado" value={money(report.metrics.totalStored)} /><MiniMetric label="Total entregado" value={money(report.metrics.totalDelivered)} /><MiniMetric label="Pendiente de entregar" value={money(report.metrics.pendingToDeliver)} /><MiniMetric label="Entregas mostradas" value={report.deliveries.length} /></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th>Fecha</Th><Th>Recibió</Th><Th>Entregó</Th><Th>Guardado</Th><Th>Entregado</Th><Th>Estado</Th><Th>Comprobante</Th></tr></thead><tbody className="divide-y divide-slate-100">{report.deliveries.map((row) => <tr key={row.id}><Td>{date(row.deliveryDate)}</Td><Td>{row.receivedBy}</Td><Td>{row.deliveredBy}</Td><Td strong>{money(row.storedAmount)}</Td><Td strong>{money(row.amount)}</Td><Td><DeliveryBadge status={row.status} /></Td><Td><Link className="font-semibold text-cyan-700" href={row.signatureReference ? `/entregas/${row.id}/comprobante` : `/entregas/${row.id}`}>{row.signatureReference ? "Abrir comprobante" : "Ver entrega"}</Link></Td></tr>)}</tbody></table></div>
        {report.deliveries.length === 0 ? <EmptyRows text="No hay entregas con los filtros seleccionados." /> : null}
      </ReportSection>

      <ReportSection description="Órdenes del mes de acuerdo con la fecha de expedición." title="Reporte de órdenes de compra">
        <div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2"><MiniMetric label="Órdenes confirmadas" value={report.metrics.purchaseOrderCount} /><MiniMetric label="Total confirmado" value={money(report.metrics.purchaseOrderTotal)} /></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th>Orden</Th><Th>Fecha</Th><Th>Proveedor</Th><Th>Estado</Th><Th>Total</Th><Th>Acciones</Th></tr></thead><tbody className="divide-y divide-slate-100">{report.purchaseOrders.map((row) => <tr key={row.id}><Td strong>{row.orderNumber}</Td><Td>{date(row.orderDate)}</Td><Td>{row.supplierLegalName}</Td><Td><OrderBadge status={row.status} /></Td><Td strong>{money(row.total)}</Td><Td><div className="flex gap-3"><Link className="font-semibold text-cyan-700" href={`/ordenes-compra/${row.id}`}>Detalle</Link>{row.status !== "draft" ? <Link className="font-semibold text-cyan-700" href={`/api/ordenes-compra/${row.id}/pdf`} target="_blank">PDF</Link> : null}{row.driveUrl ? <a className="font-semibold text-cyan-700" href={row.driveUrl} rel="noreferrer" target="_blank">Drive</a> : null}</div></Td></tr>)}</tbody></table></div>
        {report.purchaseOrders.length === 0 ? <EmptyRows text="No hay órdenes con los filtros seleccionados." /> : null}
      </ReportSection>

      <ReportSection description="Productos incluidos en órdenes confirmadas; no representa inventario físico." title="Reporte de productos vendidos">
        <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th>Referencia</Th><Th>Producto</Th><Th>Cantidad</Th><Th>Órdenes</Th><Th>Total vendido</Th><Th>Detalle</Th></tr></thead><tbody className="divide-y divide-slate-100">{report.productSales.map((row) => <tr key={`${row.productId}-${row.productReference}-${row.productName}`}><Td>{row.productReference ?? "—"}</Td><Td strong>{row.productName}<span className="ml-2 text-xs font-normal text-slate-400">{row.unit}</span></Td><Td>{quantity(row.quantity)}</Td><Td>{row.orderCount}</Td><Td strong>{money(row.soldTotal)}</Td><Td>{row.productId ? <Link className="font-semibold text-cyan-700" href={productDetailHref(context.filters!, row.productId)}>Ver órdenes</Link> : <span className="text-slate-400">Sin vínculo al catálogo</span>}</Td></tr>)}</tbody></table></div>
        {report.productSales.length === 0 ? <EmptyRows text="No hay productos en órdenes confirmadas para este periodo." /> : null}
        {context.filters.productId ? <div className="border-t border-slate-200 bg-cyan-50/40 p-4 sm:p-5"><h3 className="text-sm font-semibold text-slate-900">Órdenes relacionadas con el producto seleccionado</h3><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{report.selectedProductOrders.map((row) => <Link className="rounded-lg border border-cyan-100 bg-white p-4 hover:border-cyan-300" href={`/ordenes-compra/${row.orderId}`} key={row.orderId}><span className="font-semibold text-cyan-800">{row.orderNumber}</span><span className="mt-1 block text-xs text-slate-500">{date(row.orderDate)} · {quantity(row.quantity)} unidades · {money(row.soldTotal)}</span></Link>)}</div>{report.selectedProductOrders.length === 0 ? <p className="mt-3 text-sm text-slate-500">No hay órdenes relacionadas.</p> : null}</div> : null}
      </ReportSection>
    </>}
  </div>;
}

function ReportSection({ children, description, title }: { children: React.ReactNode; description: string; title: string }) { return <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-950">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div>{children}</section>; }
function Metric({ detail, label, tone = "cyan", value }: { detail?: string; label: string; tone?: "cyan" | "amber"; value: string }) { return <article className={`rounded-xl border bg-white p-5 shadow-sm ${tone === "amber" ? "border-amber-200" : "border-slate-200"}`}><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-400">{label}</p><p className={`mt-2 text-xl font-semibold tabular-nums ${tone === "amber" ? "text-amber-800" : "text-slate-950"}`}>{value}</p>{detail ? <p className="mt-1 text-xs text-slate-500">{detail}</p> : null}</article>; }
function MiniMetric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg bg-slate-50 px-4 py-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold tabular-nums text-slate-900">{value}</p></div>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="px-4 py-3 font-semibold">{children}</th>; }
function Td({ children, strong = false }: { children: React.ReactNode; strong?: boolean }) { return <td className={`px-4 py-3.5 align-top ${strong ? "font-semibold tabular-nums text-slate-900" : "text-slate-600"}`}>{children}</td>; }
function EmptyRows({ text }: { text: string }) { return <p className="px-5 py-8 text-center text-sm text-slate-500">{text}</p>; }
function EmptyState({ hasCompanies }: { hasCompanies: boolean }) { return <div className="mt-6 rounded-xl border border-slate-200 bg-white px-6 py-14 text-center"><p className="font-semibold text-slate-800">{hasCompanies ? "La empresa seleccionada todavía no tiene periodos." : "Primero registra una empresa y un periodo."}</p><p className="mt-2 text-sm text-slate-500">El dashboard necesita ambos datos para consolidar los movimientos.</p></div>; }
function MatchBadge({ difference, matchType }: { difference: string | null; matchType: "exact" | "similar" | "manual" | null }) { if (!matchType) return <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">Pendiente</span>; const hasDifference = Number(difference) !== 0; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${hasDifference ? "bg-violet-50 text-violet-700" : "bg-emerald-50 text-emerald-700"}`}>{hasDifference ? `Con diferencia · ${money(difference ?? "0")}` : "Exacto"}</span>; }
function DeliveryBadge({ status }: { status: DeliveryReportRow["status"] }) { const label = status === "confirmed" ? "Confirmada" : status === "cancelled" ? "Cancelada" : "Pendiente de firma"; const tone = status === "confirmed" ? "bg-emerald-50 text-emerald-700" : status === "cancelled" ? "bg-slate-100 text-slate-500" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{label}</span>; }
function OrderBadge({ status }: { status: PurchaseOrderReportRow["status"] }) { const label = status === "confirmed" ? "Confirmada" : status === "cancelled" ? "Cancelada" : "Borrador"; const tone = status === "confirmed" ? "bg-emerald-50 text-emerald-700" : status === "cancelled" ? "bg-slate-100 text-slate-500" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{label}</span>; }
function money(value: string): string { return moneyFormatter.format(Number(value)); }
function quantity(value: string): string { return quantityFormatter.format(Number(value)); }
function date(value: string): string { return new Date(`${value}T12:00:00`).toLocaleDateString("es-MX", { dateStyle: "medium" }); }
function reference(value: string | null): string { if (!value) return "—"; try { const parsed = JSON.parse(value) as Record<string, unknown>; const text = Object.entries(parsed).slice(0, 3).map(([key, item]) => `${key}: ${String(item)}`).join(" · "); return text || "—"; } catch { return value.slice(0, 120); } }
function queryParams(filters: Filters | null): URLSearchParams { const params = new URLSearchParams(); if (!filters) return params; params.set("companyId", String(filters.companyId)); params.set("periodId", String(filters.periodId)); if (filters.dateFrom) params.set("dateFrom", filters.dateFrom); if (filters.dateTo) params.set("dateTo", filters.dateTo); return params; }
function profitHref(filters: Filters | null): string { const params = queryParams(filters); return `/dashboard/utilidad${params.size ? `?${params}` : ""}`; }
function productDetailHref(filters: Filters, productId: number): string { const params = queryParams(filters); params.set("productId", String(productId)); return `/dashboard?${params}`; }
